# Course: Application of AI, Data Science and Machine Learning
# Lab 4: Recommender System

## In this lab, we will learn to build recommeder system.

### Q1. Compute cosine similiarity between these 3 documents? Use term frequency to represent the documents and remove stop words before computing the similarity. Write your interpretation about which two documents are more similar? 
corpus=[ 'Julie loves me more than Linda loves me',
         'Jane likes me more than Julie loves me', 
         'harry likes kiwi fruit']

In [1]:
corpus=[ 'Julie loves me more than Linda loves me',
         'Jane likes me more than Julie loves me', 
         'harry likes kiwi fruit']

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
vectorizer = CountVectorizer(stop_words="english")
vectors = vectorizer.fit_transform(corpus)
vectors.toarray()

array([[0, 0, 0, 1, 0, 0, 1, 2],
       [0, 0, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 0]], dtype=int64)

In [5]:
vectorizer.get_feature_names()

['fruit', 'harry', 'jane', 'julie', 'kiwi', 'likes', 'linda', 'loves']

In [23]:
cosine_sim = linear_kernel(vectors, vectors)
cosine_sim

array([[6., 3., 0.],
       [3., 4., 1.],
       [0., 1., 4.]])

In [24]:
cosine_sim2 = cosine_similarity(vectors, vectors)
cosine_sim2

array([[1.        , 0.61237244, 0.        ],
       [0.61237244, 1.        , 0.25      ],
       [0.        , 0.25      , 1.        ]])

#### You can see that document 1 and 2 are more similar. You will also notice that their is differnce between the similarity score given by the cosine_similarity() and linear_kernel(). This happens becuase byy default  'CountVectorizer' fit.transform function does not length normalizes the data.

## Q2. Repeat the above excercise but this time use tf-idf weights to convert the corpus? 

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(corpus)

In [14]:
print(tfidf_matrix)

  (0, 6)	0.5068900148458076
  (0, 7)	0.7710058432202013
  (0, 3)	0.38550292161010064
  (1, 5)	0.4598535287588349
  (1, 2)	0.6046521283053111
  (1, 7)	0.4598535287588349
  (1, 3)	0.4598535287588349
  (2, 0)	0.5286346066596935
  (2, 4)	0.5286346066596935
  (2, 1)	0.5286346066596935
  (2, 5)	0.4020402441612698


In [21]:
cosine_sim3 = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim3

array([[1.        , 0.53182464, 0.        ],
       [0.53182464, 1.        , 0.18487962],
       [0.        , 0.18487962, 1.        ]])

In [22]:
cosine_sim3 = cosine_similarity(tfidf_matrix, tfidf_matrix)
cosine_sim3

array([[1.        , 0.53182464, 0.        ],
       [0.53182464, 1.        , 0.18487962],
       [0.        , 0.18487962, 1.        ]])

#### You can see that document 1 and 2 are more similar. You will also notice that their is differnce between the similarity score given by the cosine_similarity() and linear_kernel(). This happens becuase byy default  'TfidfVectorizer()' fit.transform function length normalizes the data.

In [44]:
import pandas as pd
import numpy as np

In [51]:
movies=pd.read_csv("movies_metadata.csv", low_memory=False)
movies

adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1      False                                                NaN  65000000   
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3      False                                                NaN  16000000   
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...      ...                                                ...       ...   
45461  False                                                NaN         0   
45462  False                                                NaN         0   
45463  False                                                NaN         0   
45464  False                                                NaN         0   
45465  False                                                NaN         0   

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                         [{'id': 35, 'name': 'Comedy'}]   
...                                                  ...   
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   
45462                      [{'id': 18, 'name': 'Drama'}]   
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...   
45464                                                 []   
45465                                                 []   

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709   
1                                       NaN    8844  tt0113497   
2                                       NaN   15602  tt0113228   
3                                       NaN   31357  tt0114885   
4                                       NaN   11862  tt0113041   
...                                     ...     ...        ...   
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470   
45462                                   NaN  111109  tt2028550   
45463                                   NaN   67758  tt0303758   
45464                                   NaN  227506  tt0008536   
45465                                   NaN  461257  tt6980792   

      original_language               original_title  \
0                    en                    Toy Story   
1                    en                      Jumanji   
2                    en             Grumpier Old Men   
3                    en            Waiting to Exhale   
4                    en  Father of the Bride Part II   
...                 ...                          ...   
45461                fa                      رگ خواب   
45462                tl          Siglo ng Pagluluwal   
45463                en                     Betrayal   
45464                en          Satana likuyushchiy   
45465                en                     Queerama   

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30   
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15   
2      A family wedding reignites the ancient feud be...  ...   1995-12-22   
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22   
4      Just when George Banks has recovered from his ...  ...   1995-02-10   
...                                                  ...  ...          ...   
45461        Rising and falling between a man and woman.  ...          NaN   
45462  An artist struggles to finish his work while a...  ...   2011-11-17   
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01   
45464  In a small town live two brothers, one a minis...  ...   1917-10-21   
45465  50 years after decriminalisati

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [54]:
movies['overview'] = movies['overview'].fillna('')

In [55]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['overview'])
print(tfidf_matrix.shape)
print(tfidf.get_feature_names()[5000:5010])

(45466, 75827)
['avails', 'avaks', 'avalanche', 'avalanches', 'avallone', 'avalon', 'avant', 'avanthika', 'avanti', 'avaracious']


In [56]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
print(cosine_sim.shape)

(45466, 45466)


In [58]:
indices = pd.Series(movies.index, index=movies["title"]).drop_duplicates()

In [59]:
print(indices)

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...  
Subdue                         45461
Century of Birthing            45462
Betrayal                       45463
Satan Triumphant               45464
Queerama                       45465
Length: 45466, dtype: int64


In [62]:
# Function that takes in movie title as input and outputs most similar movies
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return movies['title'].iloc[movie_indices]

In [64]:
get_recommendations('Toy Story')

15348                                     Toy Story 3
2997                                      Toy Story 2
10301                          The 40 Year Old Virgin
24523                                       Small Fry
23843                     Andy Hardy's Blonde Trouble
29202                                      Hot Splash
43427                Andy Kaufman Plays Carnegie Hall
38476    Superstar: The Life and Times of Andy Warhol
42721    Andy Peters: Exclamation Mark Question Point
8327                                        The Champ
Name: title, dtype: object

## Code credit
 #https://www.datacamp.com/community/tutorials/recommender-systems-python
## More on Text similiarity
https://medium.com/@adriensieg/text-similarities-da019229c894
## More on recommender system
https://goodboychan.github.io/chans_jupyter/python/datacamp/natural_language_processing/2020/07/17/04-TF-IDF-and-similarity-scores.html#Cosine-similarity